---
title: "Kauliukai"
author: "MildaPie"
date: '2016 m rugsëjis 30 d '
output: html_document
---

``````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('prob')
```

## Kauliukai

 Du þaidëjai þaidþia toká þaidimà. Pirmasis þaidëjas meta tris kauliukus ir fiksuoja iðkritusiø taðkø sumà. Antrasis þaidëjas ridena du kauliukus ir skiaèiuoja iðkrituiø taðkø sumà. Laimi tas þaidëjas, kurio taðkø suma yra didesnë. Jeigu taðkø sumos yra lygios, tai, tai ekspermentas kartojamas ið naujo (ir taip kartojama tol, kol galiausiai nustatomas laimëtojas). Kokia tikimybë laimëti pirmajam þaidëjui?

```{r}

n <- 100000
i <- 1

zaid_1 <- c(rep(0, times=n))
zaid_2 <- c(rep(0, times=n))
laim_1 <- c(rep(0, times=n))

while (i<n+1) {
  zaid_1[i] <- sum(sample(1:6, 3, replace=TRUE))
  zaid_2[i] <- sum(sample(1:6, 2, replace=TRUE))
  if (zaid_1[i] > zaid_2[i]) {
    laim_1[i] <- 1
    i = i+1
  }
  else if (zaid_1[i] < zaid_2[i]) {
    laim_1[i] <- 0
    i = i+1
  }
  else i = i
}
```
Tikimybë laimëti pirmajam þaidëjui.
```{r}
mean(laim_1)
```

Nusiraðyta nuo Simonos Gritytës.
